Project Online/concertWeb/config/routes.rb
Rails.application.routes.draw do
  root :to => "concerts#index"
  resources :concerts
end

Project Online/concertWeb/app/models/concert.rb
class Concert < ActiveRecord::Base
	validates :band, 
			  :venue,
			  :city,
			  :date, 
			  :price, 
			  :description, 
			  presence: true
			  
	validates :price, numericality: true
end

Project Online/concertWeb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Project Online/concertWeb/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	  def index
      	#@concerts = Concert.all
        @concerts = Concert.select("id, band, venue, city, date, price, description").where(:date => Date.current.to_s)
        #@concertsRestantesMes = Concert.select("id, band, venue, city, date, price, description").where(:date => Date.current.to_s > "2015-04-30")
   	@concertsRestantesMes = Concert.all
    end

   	def show
        @concerts = Concert.find(params[:id])
    end
    def new
   		@concert = Concert.new
  	end

  	def edit
  		@concert = Concert.find(params[:id])
	  end

  	def create
      @concert = Concert.new(concert_params)
      if @concert.save
        redirect_to concert_path(@concert)
      else
        render :new
      end   
  	end

  	def update
 		@concert = Concert.find(params[:id])
    @concert.update(concert_params)
    if @concert.save
        redirect_to concert_path(@concert)
      else
        render :new
      end
	end

	def destroy
        @concert = Concert.find(params[:id])
        @concert.destroy
        redirect_to root_path
    end

    def showConcerts
      #@concerts = Concert.select("id, band, venue, city, date, price, description").where(:date => Date.current.to_s)
    end

  	private
    def concert_params
        params.require(:concert).permit(:band, :venue, :city, :date, :price, :description)
    end
end

Project Online/concertWeb/app/helpers/application_helper.rb
module ApplicationHelper
end

Project Online/concertWeb/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Project Online/concertWeb/app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= form_for :concert, url: concert_path(@concert), method: :patch do |f| %>
  <% @concert.errors.full_messages.each do |message| %>
    <div>*<%= message %></div>
  <% end %>


  <p>
    <%= f.label :band %><br>
    <%= f.text_field :band %>
  </p>

  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', concerts_path%>

Project Online/concertWeb/app/views/concerts/index.html.erb
<article>
	<h1>Concerts</h1>
	<% @concerts.each do |concert|%>
		<div><%= link_to concert.band, concert_path(concert)%> 
				<%= concert.date %>
				<%= link_to 'Destroy', concert_path(concert), method: :delete, data: { confirm: 'Are you sure?' } %>
				<%= link_to 'Edit', edit_concert_path(concert) %>
		</div>
	<% end %>

	<p>
	    <%= link_to 'Nuevo concierto', new_concert_path %>
	</p>

</article>
		<hr>

<aside>
		<h2> Later this month </h2>
		<% @concertsRestantesMes.each do |concertsRestantesMes|%>
		<div>
				<%= link_to concertsRestantesMes.band, concert_path(concertsRestantesMes)%> 
				<%= concertsRestantesMes.date %>
		</div>
	<% end %>


</aside>

Project Online/concertWeb/app/views/concerts/new.html.erb
<%= form_for @concert do |f| %>

<% @concert.errors.full_messages.each do |message| %>
    <div>*<%= message %></div>
  <% end %>
  
<p>
  <%= f.label :band %><br>
  <%= f.text_field :band %>
</p>

<p>
  <%= f.label :venue %><br>
  <%= f.text_field :venue %>
</p>

<p>
  <%= f.label :city %><br>
  <%= f.text_field :city %>
</p>

<p>
  <%= f.label :date %><br>
  <%= f.text_field :date %>
</p>

<p>
  <%= f.label :price %><br>
  <%= f.text_field :price %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<p>
  <%= link_to 'Back', concerts_path %>
</p>

Project Online/concertWeb/app/views/concerts/show.html.erb
<h3>
	<strong>Band:</strong>
	<%= @concerts.band %>
</h3>

<p>
	<strong>Venue:</strong>
	<%= @concerts.venue %>
</p>

<p>
	<strong>City:</strong>
	<%= @concerts.city %>
</p>

<p>
	<strong>Date:</strong>
	<%= @concerts.date %>
</p>

<p>
	<strong>Price:</strong>
	<%= @concerts.price %>
</p>

<p>
	<strong>Description:</strong>
	<%= @concerts.description %>
</p>

<%= link_to 'Back', concerts_path %>
<button type='button' id='like-button'> Like </button>

Project Online/concertWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>