semana dos/pc/config/routes.rb
Rails.application.routes.draw do
  root :to => "backpacks#index"
  resources :laptops
  resources :backpacks
end

semana dos/pc/app/models/backpack.rb
class Backpack < ActiveRecord::Base
end

semana dos/pc/app/models/laptop.rb
class Laptop < ActiveRecord::Base
end

semana dos/pc/app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
    def index
      @backpacks = Backpack.all
    end
    def show
      @backpack = Backpack.find(params[:id])
    end
    def new
   		@backpack = Backpack.new
  	end
    def edit
  		@backpack = Backpack.find(params[:id])
    end
  	def create
     	@backpack = Backpack.new(backpack_params)
     	@backpack.save
     	redirect_to backpack_path(@backpack)
  	end
	def update
 		 @backpack = Backpack.find(params[:id])
 		 @backpack.update(backpack_params)
 		 redirect_to  backpacks_path(@backpack)
	end
	def destroy
  		@backpack = Backpack.find(params[:id])
  		@backpack.destroy

  		redirect_to root_path
	end
  private
     def backpack_params
          params.require(:backpack).permit(:color, :capacity, :pockets, :waterproof, :price)
     end
end

semana dos/pc/app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
	def index
      @laptops = Laptop.all
   	end
    def show
      @laptop = Laptop.find(params[:id])
    end
    def new
   		@laptop = Laptop.new
  	end
	def edit
  		@laptop = Laptop.find(params[:id])
	end
  	def create
     	@laptop = Laptop.new(laptop_params)
     	@laptop.save
     	redirect_to laptop_path(@laptop)
  	end
	def update
 		 @laptop = Laptop.find(params[:id])
 		 @laptop.update(laptop_params)
 		 redirect_to  laptop_path(@laptop)
	end
	def destroy
  		@laptop = Laptop.find(params[:id])
  		@laptop.destroy

  		redirect_to root_path
	end
  private
     def laptop_params
          params.require(:laptop).permit(:brand, :model, :processor, :ram, :price)
     end
end

semana dos/pc/app/helpers/backpacks_helper.rb
module BackpacksHelper
end

semana dos/pc/app/helpers/laptops_helper.rb
module LaptopsHelper
end

semana dos/pc/app/views/backpacks/edit.html.erb
<h1>Editing backpack</h1>

<%= form_for :backpack, url: backpack_path(@backpack), method: :patch do |f| %>
  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>

  <p>
    <%= f.label :capacity %><br>
    <%= f.text_area :capacity %>
  </p>
<p>
    <%= f.label :pockets %><br>
    <%= f.text_area :pockets %>
  </p>
  <p>
    <%= f.label :waterproof %><br>
    <%= f.text_area :waterproof %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  <%= link_to 'Back', backpacks_path%>
<% end %>

semana dos/pc/app/views/backpacks/index.html.erb
<h1 style='text-align:center;color:green;font-size:50px;font-family:Verdana;'>Futurmanía 3000</h1>
<h1 style='background-color:yellow'>Listing backpacks</h1> 
<% @backpacks.each do |backpack|%>
 <div style='background-color:orange'>
 	<%= backpack.color %><br> <%= link_to 'Show',  backpack_path(backpack)%>
  	<%= link_to 'Edit', edit_backpack_path(backpack) %>
  	<%= link_to 'Destroy', backpack_path(backpack), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>
<p style='background-color:violet'>
    <%= link_to 'New backpack', new_backpack_path %>
</p>
<p style='text-align:center'>
	<a href='http://localhost:3000/laptops'>
	<img src='http://imagenes.web4pro.es/articulos/256/256/fixed/art_tos-p%20l10w-b-101_1.jpg'/>
	</a>
	<br>
	<a href='http://localhost:3000/laptops'>Click picture</a>
	
</p>

semana dos/pc/app/views/backpacks/new.html.erb
<%= form_for @backpack do |f| %>
 <p>
   <%= f.label :color %><br>
   <%= f.text_field :color %>
 </p>

 <p>
   <%= f.label :capacity %><br>
   <%= f.text_area :capacity %>
 </p>

   <p>
   <%= f.label :pockets %><br>
   <%= f.text_area :pockets %>
 </p>

   <p>
   <%= f.label :waterproof %><br>
   <%= f.text_area :waterproof %>
 </p>



 <p>
   <%= f.submit %>
 </p>
<% end %>

<p>
  <%= link_to 'Back', backpacks_path %>
</p>

semana dos/pc/app/views/backpacks/show.html.erb
<h3>
 <strong>Color:</strong>
 <%= @backpack.color %>
</h3>

<p>
 <strong>Capacity:</strong>
 <%= @backpack.capacity %>
</p>

<p>
 <strong>Number of pockets:</strong>
 <%= @backpack.pockets %>
</p>

<p>
 <strong>Waterproof:</strong>
 <%= @backpack.waterproof %>
</p>




<%= link_to 'Edit', edit_backpack_path(@backpack)%> |
<%= link_to 'Back', backpacks_path %>

semana dos/pc/app/views/laptops/edit.html.erb
<h1>Editing laptop</h1>

<%= form_for :laptop, url: laptop_path(@laptop), method: :patch do |f| %>
  <p>
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </p>
<p>
    <%= f.label :processor %><br>
    <%= f.text_area :processor %>
  </p>
  <p>
    <%= f.label :ram %><br>
    <%= f.text_area :ram %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <%= link_to 'Back', laptops_path%>
<% end %>

semana dos/pc/app/views/laptops/index.html.erb
<h1 style='text-align:center;color:green;font-size:50px;font-family:Verdana;'>Futurmanía 3000</h1>
<h1 style='background-color:yellow'>Listing laptops</h1> 
<% @laptops.each do |laptop|%>
 <div style='background-color:orange'>
 	<%= laptop.brand %><br> <%= link_to 'Show',  laptop_path(laptop)%>
  	<%= link_to 'Edit', edit_laptop_path(laptop) %>
  	<%= link_to 'Destroy', laptop_path(laptop), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>
<p style='background-color:violet'>
    <%= link_to 'New laptop', new_laptop_path %>
</p>
<p style='text-align:center'>
	<a href='http://localhost:3000/backpacks'>
	<img src='http://cdn.palbin.com/users/9780/images/billabong-deploy-rucksack-1401501388.png.thumb'/>
	</a>
	<br>
	<a href='http://localhost:3000/backpacks'>Click picture</a>
	
</p>

semana dos/pc/app/views/laptops/new.html.erb
<%= form_for @laptop do |f| %>
 <p>
   <%= f.label :brand %><br>
   <%= f.text_field :brand %>
 </p>

 <p>
   <%= f.label :model %><br>
   <%= f.text_area :model %>
 </p>

   <p>
   <%= f.label :processor %><br>
   <%= f.text_area :processor %>
 </p>

   <p>
   <%= f.label :ram %><br>
   <%= f.text_area :ram %>
 </p>

   <p>
   <%= f.label :price %><br>
   <%= f.text_area :price %>
 </p>

 <p>
   <%= f.submit %>
 </p>
<% end %>

<p>
  <%= link_to 'Back', laptops_path %>
</p>

semana dos/pc/app/views/laptops/show.html.erb
<h3>
 <strong>Brand:</strong>
 <%= @laptop.brand %>
</h3>

<p>
 <strong>Model:</strong>
 <%= @laptop.model %>
</p>

<p>
 <strong>Processor Brand:</strong>
 <%= @laptop.processor %>
</p>

<p>
 <strong>RAM Size (in GB):</strong>
 <%= @laptop.ram %>
</p>

<p>
 <strong>Price:</strong>
 <%= @laptop.price %>
</p>

<%= link_to 'Edit', edit_laptop_path(@laptop)%> |
<%= link_to 'Back', laptops_path %>

semana dos/pc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Futurmanía 3000</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>